# Generated by Django 4.2.6 on 2023-10-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='number_of_page',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
