# Generated by Django 4.2.6 on 2023-10-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AlterField(
            model_name='post',
            name='cost',
            field=models.PositiveIntegerField(null=True, verbose_name='Укажите цену'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='post',
            name='director',
            field=models.CharField(max_length=100, verbose_name='Укажите название модели'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Загрузите фотографию'),
        ),
        migrations.AlterField(
            model_name='post',
            name='number_of_page',
            field=models.ImageField(null=True, upload_to='', verbose_name='Укажите кол-во товара'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='Название модели'),
        ),
        migrations.AlterField(
            model_name='post',
            name='type_iphone',
            field=models.CharField(choices=[('Apple', 'Apple'), ('Samsung', 'Samsung'), ('Huawei', 'Huawei'), ('Honor', 'Honor')], max_length=100, verbose_name='Выберите модель'),
        ),
    ]
